const fs=require('fs'),vm=require('vm'),ts=require('typescript'),assert=require('assert/strict');
function buffer(channels,length,sampleRate){const data=Array.from({length:channels},()=>new Float32Array(length));return {numberOfChannels:channels,length,sampleRate,duration:length/sampleRate,getChannelData:c=>data[c]};}
let contexts=0,decodes=0;
class Offline {
 constructor(c,n,s){this.output=buffer(c,n,s);this.sources=[];this.destination={};contexts++;}
 createBufferSource(){const node={buffer:null,connect:to=>{node.to=to;},start:(when=0,offset=0)=>{node.when=when;node.offset=offset;this.sources.push(node)}};return node;}
 createGain(){return {gain:{value:1},connect(to){this.to=to;}};}
 createWaveShaper(){return {curve:null,connect(to){this.to=to;}};}
 async startRendering(){for(const source of this.sources){for(let c=0;c<2;c++){const dst=this.output.getChannelData(c),src=source.buffer.getChannelData(Math.min(c,source.buffer.numberOfChannels-1));for(let i=Math.round(source.when*this.output.sampleRate),j=Math.round(source.offset*this.output.sampleRate);i<dst.length&&j<src.length;i++,j++){const x=src[j];let value=x; if(source.to!==this.destination){const gain=source.to,curve=gain.to.curve;const pos=(Math.max(-1,Math.min(1,x*gain.gain.value))+1)*(curve.length-1)/2;const lo=Math.floor(pos),hi=Math.ceil(pos);value=curve[lo]+(curve[hi]-curve[lo])*(pos-lo);} dst[i]+=value;}}}return this.output;}
}
const sample=buffer(1,3000,1000);sample.getChannelData(0).fill(.2);
const state={targetAudioBuffer:buffer(2,25000,1000),songLengthMs:25000,files:{a:'a.wav'},audioBuffers:new Map([['a',{durationMs:3000,pcmBytes:40*1024*1024}]])};
const ctx=vm.createContext({Map,Math,Float32Array,Error,performance,previewLoadingKey:null,preparationKey:()=>"test",previewMode:{value:"keys-only"},currentRate:()=>1,appendLog:()=>{},OfflineAudioContext:Offline,preparationGeneration:1,state,audioCtx:{createBuffer:buffer,decodeAudioData:async()=>{decodes++;return sample;}},window:{bms2osu:{readAudioFile:async()=>new Uint8Array([1])}},bytesToArrayBuffer:b=>b.buffer});
const text=fs.readFileSync('renderer/renderer.ts','utf8');vm.runInContext(ts.transpile(text.slice(text.indexOf('async function renderEventBus'),text.indexOf('async function previewMixBuffer')),{target:ts.ScriptTarget.ES2022}),ctx);
(async()=>{const out=await vm.runInContext('renderEventBus([{wavId:"a",timeMs:9500},{wavId:"a",timeMs:-500}])',ctx);assert(Math.abs(out.getChannelData(0)[9999]-.16)<1e-6);assert(Math.abs(out.getChannelData(0)[10000]-.16)<1e-6);assert(Math.abs(out.getChannelData(0)[12499]-.16)<1e-6);assert.equal(out.getChannelData(0)[12500],0);assert(Math.abs(out.getChannelData(0)[0]-.16)<1e-6);assert.equal(decodes,1,'short samples are reused across windows');const loud=await vm.runInContext('renderEventBus(Array.from({length:100},()=>({wavId:"a",timeMs:1000})))',ctx);assert(loud.getChannelData(0)[1000]<.97);assert(loud.getChannelData(0)[999]===0,'no protection latency');const pending=vm.runInContext('renderEventBus([{wavId:"a",timeMs:1}])',ctx);ctx.preparationGeneration++;await assert.rejects(pending,/inputs changed/);console.log('PASS: bounded-window scheduling, negative-time tails, cross-window tails, stale render rejection (mock audio graph)');})().catch(e=>{console.error(e);process.exitCode=1;});
