export type Language = "en" | "th" | "zh";
export function isLanguage(value: unknown): value is Language { return value === "en" || value === "th" || value === "zh"; }

// English is the canonical interface text. File names, chart metadata and raw diagnostics stay intact.
export const translations: Record<string, readonly [string, string]> = {
  "Aligns BMS keysounds to an existing osu!mania beatmap, verifies timing, previews the result, and exports every audible BMS layer as playable hitsounds.": ["จัดเสียงคีย์ BMS ให้ตรงกับบีตแมป osu!mania ตรวจสอบจังหวะ ฟังตัวอย่าง และส่งออกเสียง BMS ทุกเลเยอร์เป็นฮิตซาวด์ที่เล่นได้", "将 BMS 键音与现有 osu!mania 谱面对齐，检查时序、预览结果，并将所有可听见的 BMS 音层导出为可演奏的打击音效。"],
  "Source & target": ["ต้นฉบับและเป้าหมาย", "源谱面与目标谱面"],
  "target .osu audio stays authoritative": ["ใช้เสียง .osu เป้าหมายเป็นหลัก", "以目标 .osu 音频为基准"],
  "Select BMS folder": ["เลือกโฟลเดอร์ BMS", "选择 BMS 文件夹"],
  "Select osu! folder": ["เลือกโฟลเดอร์ osu!", "选择 osu! 文件夹"],
  "Remove BMS selection": ["ล้างการเลือก BMS", "清除 BMS 选择"],
  "Remove osu selection": ["ล้างการเลือก osu!", "清除 osu! 选择"],
  "No BMS selected": ["ยังไม่ได้เลือก BMS", "尚未选择 BMS"],
  "No osu! map selected": ["ยังไม่ได้เลือกแมป osu!", "尚未选择 osu! 谱面"],
  "No BMS folder selected": ["ยังไม่ได้เลือกโฟลเดอร์ BMS", "尚未选择 BMS 文件夹"],
  "No osu! folder selected": ["ยังไม่ได้เลือกโฟลเดอร์ osu!", "尚未选择 osu! 文件夹"],
  "No folder selected": ["ยังไม่ได้เลือกโฟลเดอร์", "尚未选择文件夹"],
  "Note preview": ["ดูตัวอย่างโน้ต", "音符预览"],
  "Analyze & synchronize": ["วิเคราะห์และซิงค์", "分析并同步"],
  "BMS difficulty": ["ระดับ BMS", "BMS 难度"],
  "osu!mania difficulty": ["ระดับ osu!mania", "osu!mania 难度"],
  "Keys": ["จำนวนคีย์", "键数"],
  "target osu audio reference": ["เสียง osu! เป้าหมายอ้างอิง", "目标 osu! 参考音频"],
  "Target osu audio reference": ["เสียง osu! เป้าหมายอ้างอิง", "目标 osu! 参考音频"],
  "Original BMS audio": ["เสียง BMS ต้นฉบับ", "原始 BMS 音频"],
  "Original osu!mania song": ["เพลง osu!mania ต้นฉบับ", "原始 osu!mania 歌曲"],
  "Play preview": ["เล่นตัวอย่าง", "播放预览"],
  "Pause preview": ["พักการเล่น", "暂停预览"],
  "Preparing audio…": ["กำลังเตรียมเสียง…", "正在准备音频…"],
  "Retry preview": ["ลองเตรียมตัวอย่างอีกครั้ง", "重试预览"],
  "Preview": ["ฟังตัวอย่าง", "试听"],
  "osu audio + converted hitsounds": ["เสียง osu! + ฮิตซาวด์ที่แปลง", "osu! 音频 + 转换后的打击音效"],
  "osu audio only": ["เฉพาะเสียง osu!", "仅 osu! 音频"],
  "BMS reference only": ["เฉพาะเสียง BMS อ้างอิง", "仅 BMS 参考音频"],
  "converted hitsounds only": ["เฉพาะฮิตซาวด์ที่แปลง", "仅转换后的打击音效"],
  "Rate": ["ความเร็วเล่น", "播放速度"],
  "Beat division": ["แบ่งจังหวะ", "节拍细分"],
  "Visual grid and scroll steps; does not change note timing": ["เส้นจังหวะและระยะเลื่อน ไม่เปลี่ยนเวลาโน้ต", "用于网格和滚动步长，不改变音符时间"],
  "Scroll speed": ["ความเร็วโน้ต", "下落速度"],
  "Preparing preview": ["กำลังเตรียมตัวอย่าง", "正在准备预览"],
  "Preparing audio and note timing…": ["กำลังเตรียมเสียงและเวลาโน้ต…", "正在准备音频和音符时序…"],
  "Preparing synchronized audio and note timing…": ["กำลังเตรียมเสียงที่ซิงค์และเวลาโน้ต…", "正在准备同步音频和音符时序…"],
  "Preview ready": ["ตัวอย่างพร้อมแล้ว", "预览已就绪"],
  "Preview could not be prepared": ["เตรียมตัวอย่างไม่สำเร็จ", "无法准备预览"],
  "See Activity and retry Preview.": ["ดูบันทึกการทำงานแล้วลองเล่นอีกครั้ง", "请查看运行日志并重试预览。"],
  "mania timeline · notes fall toward judgment": ["ไทม์ไลน์ mania · โน้ตเลื่อนเข้าหาเส้นตัดสิน", "mania 时间轴 · 音符向判定线下落"],
  "Analyze maps to preview notes": ["วิเคราะห์แมปเพื่อดูตัวอย่างโน้ต", "分析谱面以预览音符"],
  "Loaded files": ["ไฟล์ที่โหลด", "已加载文件"],
  "Comparison": ["เปรียบเทียบ", "对比"],
  "Converted BMS": ["BMS ที่แปลง", "已转换 BMS"],
  "Target osu! difficulty": ["ระดับ osu! เป้าหมาย", "目标 osu! 难度"],
  "Original BMS chart": ["ชาร์ต BMS ต้นฉบับ", "原始 BMS 谱面"],
  "Original osu!mania chart": ["ชาร์ต osu!mania ต้นฉบับ", "原始 osu!mania 谱面"],
  "Overlay comparison": ["เปรียบเทียบแบบซ้อน", "叠加对比"],
  "Converted": ["แปลงแล้ว", "已转换"],
  "Original chart": ["ชาร์ตต้นฉบับ", "原始谱面"],
  "Key monitor": ["แสดงการกดคีย์", "按键监视器"],
  "Preview key activity": ["การกดคีย์ในตัวอย่าง", "预览按键活动"],
  "Follows displayed lanes. Holds stay lit until release; KPS counts note heads over one second.": ["แสดงตามเลนที่เห็น โน้ตยาวติดไฟจนปล่อย ส่วน KPS นับหัวโน้ตในหนึ่งวินาที", "跟随显示的轨道。长按灯保持到释放；KPS 统计一秒内的音符头数量。"],
  "Chart scroll changes": ["การเปลี่ยนความเร็วของชาร์ต", "谱面滚动变化"],
  "Apply source BPM / SV (visual only)": ["ใช้ BPM / SV ต้นฉบับ (เฉพาะภาพ)", "应用源 BPM / SV（仅影响显示）"],
  "Wheel scrolls the page. Hold Alt+wheel to seek 1 second; Alt+Shift+wheel steps by beat division. Middle-drag scrubs; Shift gives fine movement. Spacebar toggles play/pause.": ["ล้อเมาส์เลื่อนหน้า Alt+ล้อเมาส์เลื่อนเวลา 1 วินาที Alt+Shift+ล้อเมาส์เลื่อนตามส่วนจังหวะ ลากปุ่มกลางเพื่อเลื่อนเวลา กด Shift เพื่อละเอียดขึ้น Space เล่น/พัก", "滚轮滚动页面。Alt+滚轮跳转一秒；Alt+Shift+滚轮按节拍细分跳转。中键拖动浏览，Shift 精细移动。空格播放/暂停。"],
  "Activity": ["บันทึกการทำงาน", "运行日志"],
  "diagnostics": ["ข้อมูลตรวจสอบ", "诊断信息"],
  "Preview mixer": ["ปรับเสียงตัวอย่าง", "预览混音"],
  "Hitsound sample volume": ["ระดับเสียงฮิตซาวด์", "打击音效音量"],
  "preview + .osu output": ["ตัวอย่าง + ไฟล์ .osu ที่ส่งออก", "预览及 .osu 输出"],
  "Audio volume": ["ระดับเสียงเพลง", "音频音量"],
  "Master volume": ["ระดับเสียงหลัก", "主音量"],
  "preview comparison only": ["เฉพาะเสียงเปรียบเทียบ", "仅用于预览对比"],
  "all preview audio": ["เสียงชาร์ต (แยกจากเมโทรนอม)", "谱面音频（独立于节拍器）"],
  "map audio; metronome separate": ["เสียงชาร์ต แยกจากเมโทรนอม", "谱面音频；节拍器独立调节"],
  "Metronome": ["เมโทรนอม", "节拍器"],
  "Always follows the chart. Set Metronome volume to 0% for silent beat flashes.": ["ทำงานตามชาร์ตเสมอ ตั้งเสียงเมโทรนอมเป็น 0% เพื่อดูจังหวะโดยไม่มีเสียง", "始终跟随谱面。将节拍器音量设为 0%，即可静音显示节拍闪光。"],
  "Metronome volume": ["ระดับเสียงเมโทรนอม", "节拍器音量"],
  "independent of map audio": ["แยกจากระดับเสียงเพลง", "独立于谱面音频"],
  "Timing source": ["แหล่งจังหวะ", "时序来源"],
  "Target osu red timing points": ["จุดจังหวะสีแดงของ osu! เป้าหมาย", "目标 osu! 红线时序点"],
  "BMS native BPM / STOP timing": ["จังหวะ BPM / STOP ของ BMS ต้นฉบับ", "BMS 原始 BPM / STOP 时序"],
  "Visual metronome": ["เมโทรนอมภาพ", "可视节拍器"],
  "Meter beat indicator": ["ตัวแสดงจังหวะในห้องเพลง", "小节拍数指示器"],
  "ready": ["พร้อม", "就绪"],
  "running": ["กำลังเล่น", "播放中"],
  "Conversion behavior": ["การตั้งค่าแปลง", "转换设置"],
  "Re-snap after audio sync": ["จัดโน้ตเข้าจังหวะหลังซิงค์เสียง", "音频同步后重新吸附"],
  "Uses the analyzed .osu hitobjects first, then native BMS rhythmic phase. Switching compatible difficulties keeps this timing reference; Analyze updates it.": ["ใช้โน้ต .osu ที่วิเคราะห์ก่อน แล้วใช้โครงจังหวะ BMS การเปลี่ยนระดับที่เข้ากันจะคงจังหวะอ้างอิงนี้ไว้ กดวิเคราะห์เพื่ออัปเดต", "优先使用分析过的 .osu 音符，再参考 BMS 原始节奏。切换兼容难度会保留此时序基准；重新分析可更新它。"],
  "Resnap strategy": ["วิธีจัดเข้าจังหวะ", "吸附策略"],
  "Thorough · target + native BMS phase": ["ละเอียด · เป้าหมาย + จังหวะ BMS", "精细 · 目标 + BMS 原始节奏"],
  "Fast · conservative target capture": ["รวดเร็ว · จับจังหวะเป้าหมายแบบระมัดระวัง", "快速 · 保守匹配目标"],
  "Base tolerance": ["ระยะยอมรับพื้นฐาน", "基础容差"],
  "Resnap search sensitivity, not an audio offset. Thorough mode can search farther using timing evidence. Updates note placement; does not reanalyze audio.": ["ความไวในการค้นหาจังหวะ ไม่ใช่ออฟเซ็ตเสียง โหมดละเอียดค้นหาได้ไกลขึ้นตามหลักฐานจังหวะ อัปเดตตำแหน่งโน้ตโดยไม่วิเคราะห์เสียงใหม่", "控制吸附搜索范围，而非音频偏移。精细模式可依据时序证据扩大搜索范围。更新音符位置，不重新分析音频。"],
  "Manual Sync Correction": ["ปรับซิงค์ด้วยตนเอง", "手动同步校正"],
  "Positive shifts BMS later, negative earlier. Notes update while typing; preview audio rebuilds after a short pause. Retains automatic alignment rather than reanalyzing it. Disable re-snap to inspect the exact shift; Analyze reruns automatic alignment and resets this correction.": ["ค่าบวกเลื่อน BMS ให้ช้าลง ค่าลบเลื่อนให้เร็วขึ้น โน้ตอัปเดตขณะพิมพ์และเตรียมเสียงใหม่เมื่อหยุดพิมพ์ชั่วครู่ โดยคงผลซิงค์อัตโนมัติ ปิดการจัดเข้าจังหวะเพื่อดูการเลื่อนตรง ๆ การวิเคราะห์ใหม่จะซิงค์อีกครั้งและรีเซ็ตค่านี้", "正值使 BMS 延后，负值使其提前。输入时更新音符，短暂停顿后重新准备音频，并保留自动对齐结果。关闭吸附可查看精确偏移；重新分析会重做自动对齐并将此值归零。"],
  "Select both files, then analyze. The target .osu audio is the default synchronization and preview reference.": ["เลือกทั้งสองชาร์ตแล้ววิเคราะห์ ใช้เสียง .osu เป้าหมายเป็นค่าเริ่มต้นสำหรับซิงค์และฟังตัวอย่าง", "选择两个谱面后进行分析。默认以目标 .osu 音频作为同步和预览基准。"],
  "Sample export": ["ส่งออกเสียง", "音频样本导出"],
  "Format": ["รูปแบบ", "格式"],
  "Samples are copied into the target beatmap folder automatically.": ["คัดลอกไฟล์เสียงไปยังโฟลเดอร์บีตแมปเป้าหมายอัตโนมัติ", "音频样本将自动复制到目标谱面文件夹。"],
  "Convert / recompress to OGG": ["แปลง / บีบอัดใหม่เป็น OGG", "转换 / 重新压缩为 OGG"],
  "Keep original format": ["คงรูปแบบเดิม", "保留原格式"],
  "OGG quality": ["คุณภาพ OGG", "OGG 质量"],
  "lower = smaller": ["ต่ำลง = ไฟล์เล็กลง", "越低文件越小"],
  "Vorbis quality 3 is a modest space-saving default for keysounds.": ["Vorbis คุณภาพ 3 เป็นค่าเริ่มต้นที่ช่วยประหยัดพื้นที่เสียงคีย์", "Vorbis 质量 3 是适度节省键音空间的默认值。"],
  "Checking FFmpeg…": ["กำลังตรวจสอบ FFmpeg…", "正在检查 FFmpeg…"],
  "If a filename already exists": ["เมื่อมีชื่อไฟล์นี้อยู่แล้ว", "文件名已存在时"],
  "Keep existing file (do not replace)": ["เก็บไฟล์ที่มีอยู่ (ไม่แทนที่)", "保留已有文件（不替换）"],
  "Replace existing file": ["แทนที่ไฟล์เดิม", "替换已有文件"],
  "Different BMS samples that happen to share one basename are automatically disambiguated with their WAV id.": ["เสียง BMS ต่างกันที่มีชื่อไฟล์ซ้ำ จะเพิ่มรหัส WAV เพื่อแยกไฟล์อัตโนมัติ", "不同 BMS 样本如有相同文件名，会自动添加 WAV 编号以区分。"],
  "Convert difficulty + export samples": ["แปลงชาร์ตและส่งออกเสียง", "转换难度并导出音频"],
  "Original-format copy selected — FFmpeg is not required.": ["เลือกคัดลอกรูปแบบเดิม ไม่ต้องใช้ FFmpeg", "已选择原格式复制，无需 FFmpeg。"],
  "FFmpeg not found. Features that need it will show an install prompt with the winget command.": ["ไม่พบ FFmpeg ฟังก์ชันที่ต้องใช้จะแสดงวิธีติดตั้งด้วยคำสั่ง winget", "未找到 FFmpeg。需要它的功能会显示包含 winget 命令的安装提示。"],
  "Reused the recent audio analysis: artist, title, timing and audio match.": ["ใช้ผลวิเคราะห์เสียงล่าสุดซ้ำ ศิลปิน ชื่อเพลง จังหวะและเสียงตรงกัน", "复用最近的音频分析：艺人、曲名、时序和音频均匹配。"],
  "Selection changed — analyze this BMS / osu pair before converting.": ["เปลี่ยนการเลือกแล้ว โปรดวิเคราะห์คู่ BMS / osu! นี้ก่อนแปลง", "选择已改变，请先分析此 BMS / osu! 组合再转换。"],
  "Choose Note preview for one chart, or select both files to synchronize.": ["เลือกดูโน้ตสำหรับชาร์ตเดียว หรือเลือกทั้งสองชาร์ตเพื่อซิงค์", "单个谱面可进行音符预览，选择两个谱面可进行同步。"],
  "Pair verification failed — see the popup and diagnostics for the exact checks.": ["ตรวจสอบคู่ชาร์ตไม่ผ่าน ดูรายละเอียดในหน้าต่างแจ้งเตือนและบันทึก", "谱面组合验证失败，请查看弹窗和诊断信息。"],
  "Pair verification uncertain — analysis cancelled by user.": ["ผลตรวจสอบคู่ชาร์ตไม่แน่ชัด ผู้ใช้ยกเลิกการวิเคราะห์", "谱面组合验证不确定，用户已取消分析。"],
  "Language": ["ภาษา", "语言"],
  "BMS / osu! pair verification failed": ["ตรวจสอบคู่ BMS / osu! ไม่ผ่าน", "BMS / osu! 组合验证失败"],
  "The selected BMS and .osu look clearly incompatible, so preview and conversion were blocked.": ["BMS และ .osu ที่เลือกดูไม่ตรงกัน จึงระงับการฟังตัวอย่างและแปลง", "所选 BMS 与 .osu 明显不匹配，因此已阻止预览和转换。"],
  "BMS / osu! pair could not be fully verified": ["ยังตรวจสอบคู่ BMS / osu! ได้ไม่ครบ", "无法完全验证 BMS / osu! 组合"],
  "This pair is plausible, but some verification signals are weak.": ["คู่ชาร์ตนี้เป็นไปได้ แต่หลักฐานบางส่วนยังไม่ชัดเจน", "此组合可能匹配，但部分验证信号较弱。"],
  "NOW": ["ตอนนี้", "当前"],
  "Select BMS song folder": ["เลือกโฟลเดอร์เพลง BMS", "选择 BMS 歌曲文件夹"],
  "Select osu!mania song folder": ["เลือกโฟลเดอร์เพลง osu!mania", "选择 osu!mania 歌曲文件夹"],
  "Chart folder": ["โฟลเดอร์ชาร์ต", "谱面文件夹"],
  "Some files were rejected; supported difficulties are available.": ["บางไฟล์ไม่รองรับ สามารถเลือกระดับที่รองรับได้", "部分文件被拒绝，仍可选择受支持的难度。"],
  "No supported charts found in this folder.": ["ไม่พบชาร์ตที่รองรับในโฟลเดอร์นี้", "此文件夹中没有受支持的谱面。"],
  "Could not read chart folder": ["อ่านโฟลเดอร์ชาร์ตไม่สำเร็จ", "无法读取谱面文件夹"],
  "Select a BMS file": ["เลือกไฟล์ BMS", "选择 BMS 文件"],
  "Select Target .osu File": ["เลือกไฟล์ .osu เป้าหมาย", "选择目标 .osu 文件"],
  "Continue anyway": ["ดำเนินการต่อ", "仍然继续"],
  "Cancel": ["ยกเลิก", "取消"],
  "OK": ["ตกลง", "确定"],
  "FFmpeg is required": ["ต้องใช้ FFmpeg", "需要 FFmpeg"],
  "Copy winget command": ["คัดลอกคำสั่ง winget", "复制 winget 命令"],
  "Retry": ["ลองอีกครั้ง", "重试"],
  "Not now": ["ไว้ก่อน", "暂不"],
  "Command copied": ["คัดลอกคำสั่งแล้ว", "命令已复制"],
  "The FFmpeg winget command was copied to your clipboard.": ["คัดลอกคำสั่ง winget สำหรับ FFmpeg ไปยังคลิปบอร์ดแล้ว", "FFmpeg 的 winget 命令已复制到剪贴板。"],
  "Install FFmpeg with Windows Package Manager, then click Retry.": ["ติดตั้ง FFmpeg ด้วย Windows Package Manager แล้วคลิกลองอีกครั้ง", "使用 Windows 软件包管理器安装 FFmpeg，然后点击重试。"],
  "You can also set FFMPEG_PATH or place ffmpeg.exe beside the installed app.": ["สามารถตั้ง FFMPEG_PATH หรือวาง ffmpeg.exe ข้างแอปที่ติดตั้งได้", "也可设置 FFMPEG_PATH，或将 ffmpeg.exe 放在已安装应用旁。"],
  "Paste it into Windows Terminal or PowerShell, wait for installation to finish, then click Retry or use the feature again.": ["วางคำสั่งใน Windows Terminal หรือ PowerShell รอให้ติดตั้งเสร็จ แล้วคลิกลองอีกครั้งหรือใช้ฟังก์ชันใหม่", "将命令粘贴到 Windows Terminal 或 PowerShell，等待安装完成后点击重试或再次使用该功能。"],
};

export function translateText(text: string, language: Language): string {
  if (language === "en") return text;
  const slot = language === "th" ? 0 : 1;
  const exact = translations[text];
  if (exact) return exact[slot];
  if (text.includes("\n")) return text.split("\n").map(line=>translateText(line,language)).join("\n");
  let m: RegExpMatchArray | null;
  if ((m = text.match(/^beat (\d+)\/(\d+)$/))) return language === "th" ? `จังหวะ ${m[1]}/${m[2]}` : `第 ${m[1]}/${m[2]} 拍`;
  if ((m = text.match(/^Key (\d+)$/))) return language === "th" ? `คีย์ ${m[1]}` : `按键 ${m[1]}`;
  if ((m = text.match(/^FFmpeg ready(.*)$/))) return (language === "th" ? "FFmpeg พร้อม" : "FFmpeg 已就绪") + m[1];
  if ((m = text.match(/^Audio prepared: (.+) \/ (.+) s of song · elapsed (.+) s$/))) return language === "th" ? `เตรียมเสียง ${m[1]} / ${m[2]} วินาทีของเพลง · ใช้เวลา ${m[3]} วินาที` : `音频已准备 ${m[1]} / ${m[2]} 秒 · 已用时 ${m[3]} 秒`;
  if ((m = text.match(/^Manual correction (.+) ms · automatic alignment retained\. Notes updated; preview audio is being prepared\.$/))) return language === "th" ? `ปรับด้วยตนเอง ${m[1]} ms · คงซิงค์อัตโนมัติ อัปเดตโน้ตแล้ว กำลังเตรียมเสียง` : `手动校正 ${m[1]} ms · 保留自动对齐。音符已更新，正在准备预览音频。`;
  if ((m = text.match(/^Original (BMS|osu!mania) chart loaded — native lanes and timing; no conversion or resnap\.$/))) return language === "th" ? `โหลดชาร์ต ${m[1]} ต้นฉบับแล้ว ใช้เลนและจังหวะเดิม ไม่มีการแปลงหรือจัดเข้าจังหวะ` : `已加载原始 ${m[1]} 谱面，保留原始轨道和时序，不进行转换或吸附。`;
  if ((m = text.match(/^Synchronized (\d+) audible BMS events\. Target osu audio remains the default preview reference; BMS-native metronome is available as an alternate check\.$/))) return language === "th" ? `ซิงค์เสียง BMS ${m[1]} รายการแล้ว ใช้เสียง osu! เป้าหมายเป็นหลัก และเลือกเมโทรนอม BMS เพื่อเปรียบเทียบได้` : `已同步 ${m[1]} 个 BMS 音频事件。默认以目标 osu! 音频作为预览基准，也可使用 BMS 原始节拍器进行对照。`;
  if (/^(Original (BMS|osu!mania) ·|Target \d+K ·|Converted \d+K)/.test(text)) {
    const words: Record<string, readonly [string,string]> = { Original:["ต้นฉบับ","原始"], Target:["เป้าหมาย","目标"], Converted:["แปลงแล้ว","已转换"], lanes:["เลน","轨"], keys:["คีย์","键"], notes:["โน้ต","音符"], objects:["โน้ต","音符"], speed:["ความเร็ว","速度"], "near-collision shifts":["รายการเลื่อนหลบโน้ต","近碰撞偏移"] };
    return text.replace(/near-collision shifts|\b(Original|Target|Converted|lanes|keys|notes|objects|speed)\b/g, word=>words[word][slot]);
  }
  return text;
}
